### ISSUE TITLE
can you make quick start guide

### ISSUE THREAD

**Issue by iswami28** [ml1nk/robotjs-browser#1]
how its works

**Comment by ml1nk** [comment]
There was already an example included, which shows the usage of robotjs through the browser (readme is updated). After fixing a wrong file path with newer versions of socket.io-client, you should be able to start the server in the console on the new version and then open the example under http://localhost:7569/.

Basically the scripts allows you to use robotjs over socket.io and adds some functions for positioning the mouse on DOM elements. The positioning is not perfect, but works at least in fullscreen reliable. 

Is it working?
